---
# Cloudwatch Exporter metrics configuration (cloudwatch_metrics.yml)
cloudwatch_metrics_enable: true
auto_scaling: no
billing: no
custom: no
dynamo_db: no
ebs: no
ec2: no
elasti_cache: no
events: no
lambda: no
logs: no
network_elb: no
rds: true
s3: no
transit_gateway: no
trusted_advisor: no
usage: no
